
package trab1.both.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DirServerWSService", targetNamespace = "http://tp2/", wsdlLocation = "http://127.0.0.1:8080/comunidade-1?wsdl")
public class DirServerWSService
    extends Service
{

    private final static URL DIRSERVERWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(trab1.both.ws.DirServerWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = trab1.both.ws.DirServerWSService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/comunidade-1?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/comunidade-1?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DIRSERVERWSSERVICE_WSDL_LOCATION = url;
    }

    public DirServerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirServerWSService() {
        super(DIRSERVERWSSERVICE_WSDL_LOCATION, new QName("http://tp2/", "DirServerWSService"));
    }

    /**
     * 
     * @return
     *     returns DirServerWS
     */
    @WebEndpoint(name = "DirServerWSPort")
    public DirServerWS getDirServerWSPort() {
        return super.getPort(new QName("http://tp2/", "DirServerWSPort"), DirServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirServerWS
     */
    @WebEndpoint(name = "DirServerWSPort")
    public DirServerWS getDirServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tp2/", "DirServerWSPort"), DirServerWS.class, features);
    }

}
